import "./styles.css";

const SectionFirst = ({ animateFirstSection }) => {
   return (
      <div className={`container-first ${animateFirstSection ? "animate" : ""}`}>
         <h2>Section - First</h2>
         <p className="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec purus eget neque lobortis dapibus. Integer tristique congue justo, id aliquet elit eleifend ac. Sed pellentesque ipsum at lectus efficitur efficitur. In posuere elit ut ante feugiat porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst. Pellentesque elit eros, suscipit at eros id, facilisis ultricies lectus. Nam laoreet elit magna, eget auctor tellus sodales pulvinar. Vestibulum facilisis ut leo eu porttitor.
         Cras et nisl mollis, tincidunt sem ac, ornare risus. Morbi laoreet nulla vel mauris viverra finibus. In aliquam augue at libero pellentesque, non hendrerit lectus varius. Praesent ut felis consectetur, ultricies diam nec, tempor dui. Quisque bibendum dui in tempus accumsan. Phasellus quis dui dictum, laoreet lacus quis, dictum nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas at justo mi. Curabitur lobortis est eros, vitae ornare turpis blandit eu. Nam tincidunt enim in nunc placerat, eu molestie turpis pharetra. Phasellus ac interdum elit, eu molestie turpis. Vivamus venenatis felis vel augue tincidunt volutpat. Vestibulum accumsan pellentesque leo. Proin tincidunt sapien tortor, tempor tincidunt ex viverra a. Aenean ac orci velit. Nulla gravida aliquam est, a fermentum mauris mattis at.
         Vestibulum non libero ac justo venenatis hendrerit. Nunc lorem ex, dignissim vel ligula eu, facilisis dignissim nibh. Sed gravida hendrerit euismod. Integer ullamcorper rhoncus lectus et commodo. Sed non euismod lectus. Nullam eu lacinia justo, eu posuere sapien. Nulla non metus congue, porta velit vel, bibendum sem. Duis non pretium turpis. Mauris molestie lectus ac quam vulputate, at porta justo commodo. Cras tortor turpis, pretium vitae justo sit amet, rutrum molestie diam. Ut consectetur lectus in est tincidunt, nec facilisis libero pellentesque. Suspendisse potenti. Phasellus eu ex ac libero ultricies egestas. Cras ut tristique neque, non luctus nibh. Nam eget rhoncus nisi.         Ut a elit bibendum massa laoreet iaculis. Cras eget maximus odio. Nam at sapien nec diam viverra venenatis. Duis id sapien aliquet, maximus nunc malesuada, mollis leo. Pellentesque mattis ut diam quis vestibulum. Donec pellentesque, lectus vitae cursus sollicitudin, mauris nunc malesuada arcu, eu congue velit nisi nec elit. Quisque quis lorem urna. Curabitur a lectus accumsan, aliquam elit a, molestie erat. Morbi eu fermentum est, ac tincidunt diam.
         Donec augue mauris, sollicitudin ac lacus id, blandit rutrum nulla. Praesent porta mi faucibus lectus dignissim, ut accumsan tellus imperdiet. Phasellus efficitur leo ac turpis vulputate, convallis dictum libero tristique. Integer auctor nulla eget augue bibendum, at bibendum ligula rhoncus. Aenean a lacinia elit. Nam at nulla erat. Vestibulum vitae metus et dolor vestibulum aliquet. Nulla quis faucibus sapien, nec aliquam purus. Duis pharetra a enim non suscipit. Aenean vitae nisi id purus vestibulum tincidunt sed et dui. Vestibulum sed arcu varius, finibus odio nec, ullamcorper urna. Duis nec metus velit. Vivamus tristique ex ut ipsum fermentum, ac blandit sem commodo. Sed leo metus, vestibulum id erat et, ultricies vulputate lorem. </p>
      </div>
   );
}

export default SectionFirst;